name: Frisking
main: me.aaomidi.frisking.Main
version: 0.1
website: http://www.deityhosting.com
authors:
  - aaomidi
description: >
 A plugin that checks for drugs!
commands:
  check:
    description: Enables the explosive spell!
    permissions: friking.check